### ISSUE TITLE
Profile support

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/beyond-ctl#6]
```
beyondctl profile add local fs:///tmp
beyondctl profile del local
```

```
beyondctl ls local:/
beyoncctl cp local:/xxx remote:/qqq
```

**Comment by Prnyself** [comment]
Maybe `beyondctl profile list` is needed in case of someone forgot its profile.

**Comment by Xuanwo** [comment]
I don't know if `profile` is a good name. 

- `git` uses `remote` instead.
- minio uses `alias`.

**Comment by Prnyself** [comment]
> I don't know if `profile` is a good name.
> 
>     * `git` uses `remote` instead.
> 
>     * minio uses `alias`.

How about `identity`? Which keeps the same as `identity` in `BeyondTP`.

**Comment by Xuanwo** [comment]
> How about `identity`? Which keeps the same as `identity` in `BeyondTP`.

`BeyondTP`'s `identity` only carry `credential` and `endpoint`, it's not suitable for us.
